app = "flaskstdsearch"

primary_region = "fra"

[build]
  image = "python:3.10"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]
